---
title: "Ameriflux data"
author: "Wesley Rancher, James Lamping"
date: "2025-05-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(amerifluxr)
library(tidyverse)
library(lubridate)
library(minpack.lm)
library(pander)
library(data.table)
library(nls2)
```

Environment variables (change these)

```{r}
username <- "wesr"
email <- "wesr@uoregon.edu"
var <- "SWC"
```

Filtering

```{r}
sites <- amf_site_info()
sites_dt <- data.table::as.data.table(sites)
pander::pandoc.table(sites_dt[c(1:3), ])
pander::pandoc.table(sites_dt[, .N])
pander::pandoc.table(sites_dt[!is.na(DATA_START), .N])
pander::pandoc.table(sites_dt[!is.na(DATA_START), .N, by = .(DATA_POLICY)])
pander::pandoc.table(sites_dt[, .N, by = "IGBP"])
pander::pandoc.table(sites_dt[!is.na(DATA_START), .N, by = "IGBP"][order(IGBP)])
pander::pandoc.table(sites_dt[!is.na(DATA_START), .N, by = .(IGBP, DATA_POLICY)][order(IGBP)])
crop_ls <- sites_dt[IGBP %in% c("CSH", "DBF", "DNF", "EBF", "ENF", "MF", "OSH", "SAV", "WET", "WSA") &
                      !is.na(DATA_START) &
                      LOCATION_LAT >40 &
                      LOCATION_LONG > -130,
                    .(SITE_ID, SITE_NAME, DATA_START, DATA_END)]
pander::pandoc.table(crop_ls[c(1:10),])
```

Metadata

```{r}
#get metadata
metadata_aval <- data.table::as.data.table(amf_list_metadata())
pander::pandoc.table(metadata_aval[c(1:3), c(1:10)])
metadata_aval_sub <- as.data.table(amf_list_metadata(site_set = crop_ls$SITE_ID))

## what sort of data is available
data_aval <- data.table::as.data.table(amf_list_data(site_set = crop_ls$SITE_ID))
pander::pandoc.table(data_aval[c(1:10), ])

data_aval_gpp <- data_aval[data_aval$BASENAME %in% c("GPP"),
                           .(SITE_ID, BASENAME)]
data_aval_nee <- data_aval[data_aval$BASENAME %in% c("NEE"),
                           .(SITE_ID, BASENAME)]
data_aval_swc <- data_aval[data_aval$BASENAME %in% c("SWC"),
                           .(SITE_ID, BASENAME)]
select_sites = amf_summarize_data(site_set = crop_ls$SITE_ID, var_set = c("GPP")) %>% distinct(SITE_ID)
#pander::pandoc.table(data_sum[c(1:10), ])
```

Temperature response curves

```{r}
fit_moisture_response_flux_amf <- function(site_id, user_id = username, user_email = email,
                                           variable = var, out_dir = tempdir()) {
  
  # download BASE-BADM data
  message(paste("Downloading AmeriFlux data for", site_id))
  file_path <- amf_download_base(
    user_id = user_id,
    user_email = user_email,
    site_id = site_id,
    data_product = "BASE-BADM",
    data_policy = "CCBY4.0",
    agree_policy = TRUE,
    intended_use = "model",
    intended_use_text = paste0(variable, " response fitting"),
    out_dir = out_dir,
    verbose = FALSE
  )
  
  # read and clean
  base_raw <- amf_read_base(file = file_path, unzip = TRUE, parse_timestamp = TRUE)

  df <- base_raw %>%
    mutate(
      GPP = rowMeans(select(., contains("GPP")), na.rm = TRUE),
      ENV_VAR = rowMeans(select(., contains(variable)), na.rm = TRUE)
    ) %>%
    filter(!is.na(GPP), !is.na(ENV_VAR)) %>%
    mutate(across(c(TIMESTAMP_START, TIMESTAMP_END), ymd_hm),
           year = year(TIMESTAMP_START),
           month = month(TIMESTAMP_START))

  # monthly max aggregation
  monthly <- df %>%
    group_by(year, month) %>%
    summarise(
      var = max(ENV_VAR, na.rm = TRUE),
      gpp = max(GPP, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    filter(!is.na(var), !is.na(gpp))

  # normalize GPP
  gpp_min <- min(monthly$gpp)
  gpp_max <- max(monthly$gpp)
  monthly <- monthly %>%
    mutate(
      rel_gpp = round((gpp - gpp_min) / (gpp_max - gpp_min), 3)
    )

  # starting coefficients
  #ppdf_1 <- ceiling(mean(monthly$var, na.rm = TRUE))
  ppdf_1 <- ceiling(quantile(monthly$var, probs = 0.7, na.rm = TRUE))
  #ppdf_2 <- ceiling(max(monthly$var, na.rm = TRUE))
  ppdf_2 <- ceiling(quantile(monthly$var, probs = 0.98, na.rm = TRUE))
  ppdf_3 <- 0.75
  ppdf_4 <- 2

  # moisture response function (same form as temperature response function)
  calculate_fitted_RP <- function(var, coef_1, coef_2, coef_3, coef_4) {
    frac <- (coef_2 - var) / (coef_2 - coef_1)
    if_else(frac > 0,
            exp(coef_3 / coef_4 * (1 - frac^coef_4)) * (frac^coef_3),
            0)
  }

  # fit model
  fit_df <- monthly %>%
    select(var, rel_gpp)
  
  fit <- nls2(rel_gpp ~ calculate_fitted_RP(var, coef_1, coef_2, coef_3, coef_4),
                           data = fit_df,
                           start = list(coef_1 = ppdf_1,
                                        coef_2 = ppdf_2,
                                        coef_3 = ppdf_3,
                                        coef_4 = ppdf_4),
                           trace = TRUE,
                           nls.control(maxiter = 10000, 
                                       printEval = FALSE,
                                       warnOnly = TRUE))

  # generate fitted curve
  pred_var <- seq(min(fit_df$var), max(fit_df$var), length.out = 500)
  pred_gpp <- calculate_fitted_RP(pred_var,
                                  coef(fit)[1],
                                  coef(fit)[2],
                                  coef(fit)[3],
                                  coef(fit)[4])

  # plot
  plot <- ggplot(fit_df, aes(x = var, y = rel_gpp)) +
    geom_point(color = "forestgreen", alpha = 0.6) +
    geom_line(data = tibble(var = pred_var, pred = pred_gpp),
              aes(x = var, y = pred), color = "red", linewidth = 1.2) +
    labs(title = paste0("GPP–", variable, " Curve: ", site_id),
         x = "Soil Water Content (%)",
         y = "Relative GPP (0–1)") +
    theme_bw()

  return(list(
    site = site_id,
    fit = fit,
    coefficients = coef(fit),
    fitted_curve = tibble(var = pred_var, rel_gpp = pred_gpp),
    data = fit_df,
    plot = plot
  ))
}
```

Export results

```{r}
site_ids <- c("CA-Ca1", "CA-Ca2")  # add your site ids
moisture.results <- lapply(select_sites$SITE_ID, function(site) {
  tryCatch(
    {
      fit_moisture_response_flux_amf(
        site_id = site,
        user_id = username,
        user_email = email
      )
    },
    error = function(e) {
      message(paste("Skipping", site, "due to error:", e$message))
      return(NULL)
    }
  )
})

for (res in moisture.results) {
  if (!is.null(res)) {
    print(res$plot)
    Sys.sleep(1)
  }
}

```